export const jobs = [
  {
    id: "1",
    jobTitle: "Frontend Developer",
    typesOfEmployment: ["Full-Time", "Remote"],
    categories: ["Engineering", "Technology"],
    capacity: 10,
    currentApplicants: 5,
  },
  {
    id: "2",
    jobTitle: "Graphic Designer",
    typesOfEmployment: ["Part-Time", "Remote"],
    categories: ["Design", "Marketing"],
    capacity: 5,
    currentApplicants: 2,
  },
  {
    id: "3",
    jobTitle: "Marketing Specialist",
    typesOfEmployment: ["Full-Time"],
    categories: ["Marketing", "Sales"],
    capacity: 8,
    currentApplicants: 3,
  },
  {
    id: "4",
    jobTitle: "Business Analyst",
    typesOfEmployment: ["Full-Time", "Contract"],
    categories: ["Business", "Finance"],
    capacity: 7,
    currentApplicants: 4,
  },
  {
    id: "5",
    jobTitle: "Sales Manager",
    typesOfEmployment: ["Full-Time"],
    categories: ["Sales", "Business"],
    capacity: 6,
    currentApplicants: 6,
  },
  {
    id: "6",
    jobTitle: "Data Scientist",
    typesOfEmployment: ["Full-Time", "Remote"],
    categories: ["Technology", "Engineering"],
    capacity: 12,
    currentApplicants: 8,
  },
  {
    id: "7",
    jobTitle: "Content Writer",
    typesOfEmployment: ["Part-Time", "Remote"],
    categories: ["Marketing", "Technology"],
    capacity: 4,
    currentApplicants: 2,
  },
  {
    id: "8",
    jobTitle: "Finance Assistant",
    typesOfEmployment: ["Internship"],
    categories: ["Finance", "Business"],
    capacity: 3,
    currentApplicants: 1,
  },
  {
    id: "9",
    jobTitle: "UX/UI Designer",
    typesOfEmployment: ["Full-Time"],
    categories: ["Design", "Technology"],
    capacity: 5,
    currentApplicants: 4,
  },
  {
    id: "10",
    jobTitle: "Engineering Manager",
    typesOfEmployment: ["Full-Time", "Contract"],
    categories: ["Engineering", "Business"],
    capacity: 9,
    currentApplicants: 7,
  },
  {
    id: "11",
    jobTitle: "Remote Support Specialist",
    typesOfEmployment: ["Remote", "Part-Time"],
    categories: ["Technology", "Sales"],
    capacity: 6,
    currentApplicants: 3,
  },
  {
    id: "12",
    jobTitle: "Marketing Assistant",
    typesOfEmployment: ["Internship"],
    categories: ["Marketing", "Business"],
    capacity: 2,
    currentApplicants: 1,
  },
];
